//
//  CharacterDetailsWireframe.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 01/02/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CharacterDetailsWireframe: BaseWireframe<CharacterDetailsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(character: CharacterData) {
        let moduleViewController = CharacterDetailsViewController()
        super.init(viewController: moduleViewController)

        let interactor = CharacterDetailsInteractor(marvelService: MarvelService.shared)
        let presenter = CharacterDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, character: character)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CharacterDetailsWireframe: CharacterDetailsWireframeInterface {

}
