//
//  CharacterDetailsInterfaces.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 01/02/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CharacterDetailsWireframeInterface: WireframeInterface {
}

protocol CharacterDetailsViewInterface: ViewInterface {
    @MainActor func setTitle(_ title: String)
    @MainActor func showData(sections: [CharacterDetailsViewModel.Section])
}

protocol CharacterDetailsPresenterInterface: PresenterInterface {
    func configure() async
}

protocol CharacterDetailsInteractorInterface: InteractorInterface {
    func getComics(characterId: Int) async throws -> [ComicData]
}
