//
//  CharactersListPresenter.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 31/01/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class CharactersListPresenter {

    // MARK: - Private properties -

    private unowned let view: CharactersListViewInterface
    private let interactor: CharactersListInteractorInterface
    private let wireframe: CharactersListWireframeInterface

    private var isLoading: Bool = false
    private var searchTerm: String? = nil
    private var hasNextPage: Bool = false
    private var characters: [CharacterData] = []

    // MARK: - Lifecycle -

    init(
        view: CharactersListViewInterface,
        interactor: CharactersListInteractorInterface,
        wireframe: CharactersListWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CharactersListPresenter: CharactersListPresenterInterface {
    func search(for searchTerm: String?) async {
        self.searchTerm = searchTerm
        self.resetState()
        await view.clearError()
        await self.view.showResults(sections: self.constructSections())
        // Makes UI look nicer :)
        try? await Task.sleep(nanoseconds: 1_000_000_000)
        await self.performSearch()
    }

    func loadNextPage() async {
        if isLoading {
            print("isLoading")
            return
        }
        await self.performSearch()
        print("performedSearch")
    }

    func didSelect(character: CharacterData) {
        wireframe.navigateToCharacterDetails(character: character)
    }
}

private extension CharactersListPresenter {

    func resetState() {
        hasNextPage = false
        isLoading = false
        characters.removeAll()
    }

    func constructSections() -> [CharactersListViewModel.Section] {
        if characters.isEmpty {
            let items: [CharactersListViewModel.Item] = (0..<10).map { .characterLoading(index: $0)}
            return [.init(sectionIdentifier: .heroes, items: items)]
        }
        let characterItems: [CharactersListViewModel.Item] = characters.map { .character(data: $0) }
        var sections: [CharactersListViewModel.Section] = [.init(sectionIdentifier: .heroes, items: characterItems)]
        if hasNextPage {
            sections.append(.init(sectionIdentifier: .loading, items: [.loadingNextPage]))
        }
        return sections
    }

    func performSearch() async {
        do {
            isLoading = true
            let responseData = try await self.interactor.search(for: self.searchTerm, offset: self.characters.count, limit: 10)
            isLoading = false
            self.characters.append(contentsOf: responseData.results ?? [])
            self.hasNextPage = responseData.total > self.characters.count
            await self.view.showResults(sections: self.constructSections())
        } catch AFError.explicitlyCancelled {
            // Mute explicitly cancelled error
        } catch {
            if characters.isEmpty {
                await view.clearResults()
            }
            let errorMessage = getMessageForError(error)
            await view.showError(errorMessage: errorMessage)
        }
    }

    func getMessageForError(_ error: Error) -> String {
        var errorMessage = "An unexpected error occurred."
        switch error {
        case let error as NSError:
            switch (error.domain, error.code) {
            case ("Alamofire.AFError", 13):
                errorMessage = "Your internet connection appears to be offline. Please check your network settings."
            default:
                break
            }
        default:
            break
        }
        return errorMessage
    }

}
