//
//  CharactersListWireframe.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 31/01/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CharactersListWireframe: BaseWireframe<CharactersListViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = CharactersListViewController()
        super.init(viewController: moduleViewController)

        let interactor = CharactersListInteractor(marvelService: MarvelService.shared)
        let presenter = CharactersListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CharactersListWireframe: CharactersListWireframeInterface {
    func navigateToCharacterDetails(character: CharacterData) {
        navigationController?.pushWireframe(CharacterDetailsWireframe(character: character))
    }
}
