//
//  CharactersListInteractor.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 31/01/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CharactersListInteractor {

    private let marvelService: MarvelServiceInterface

    init(marvelService: MarvelServiceInterface) {
        self.marvelService = marvelService
    }
}

// MARK: - Extensions -

extension CharactersListInteractor: CharactersListInteractorInterface {

    func search(for term: String?, offset: Int, limit: Int) async throws -> CharactersResponseData {
        return try await marvelService.getCharacters(nameStartsWith: term, order: "name", offset: offset, limit: limit).data
    }

}
