//
//  CharactersListInterfaces.swift
//  AsyncAwaitMarvelHeroes
//
//  Created by Marsel Tzatzos on 31/01/2022.
//  Copyright (c) 2022 QQ. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CharactersListWireframeInterface: WireframeInterface {
    func navigateToCharacterDetails(character: CharacterData)
}

protocol CharactersListViewInterface: ViewInterface {
    @MainActor func clearResults()
    @MainActor func showResults(sections: [CharactersListViewModel.Section])
}

protocol CharactersListPresenterInterface: PresenterInterface {
    func search(for searchTerm: String?) async
    func loadNextPage() async
    func didSelect(character: CharacterData)
}

protocol CharactersListInteractorInterface: InteractorInterface {
    func search(for term: String?, offset: Int, limit: Int) async throws -> CharactersResponseData
}
